// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arexjpknfknerwtwycpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyZXhqcGtuZmtuZXJ3dHd5Y3ByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NDcwODcsImV4cCI6MjA2OTIyMzA4N30.eWBni54xHVnkKCo5wTQB9HVZZtmhkZL7AwMHZzuubos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});